### ISSUE TITLE
Cannot display edges of a cosmos db

### ISSUE THREAD

**Issue by viebel** [Azure-Samples/azure-cosmos-db-dotnet-graphexplorer#17]
We connected the app to our graph on CosmosDB. 
But we were not able to display edges when the result of the query is a Graph.
For instance,
```
g.V().limit(5)
```

On azure data explorer, we see both vertices and edges while on the app we see only vertices.

**Comment by alexdrenea** [comment]
Well, your query asks only for the vertices so essentially there are no edges to display.
Not sure how the Azure portal implemented it, but the way I do it in Graph Explorer is to make sure I query for the edges as well

```g.V().limit(5); g.V().limit(5).bothE()```

**Comment by viebel** [comment]
I tried your approach.
The problem is that cosmos doesn't support multiple-query at once

**Comment by alexdrenea** [comment]
Maybe I am missing something, but in Graph Explorer, if you write multiple queries, separated by semicolon, just like my example above, all queries will be ran and their results will be aggregated in the Graph representation.

**Comment by viebel** [comment]
You are right.
I was confused with the online azure data explorer.
It works!
