### ISSUE TITLE
App connects to DocumentDB, but QuickStart creates a GraphDB

### ISSUE THREAD

**Issue by philemon33** [Azure-Samples/azure-cosmos-db-dotnet-graphexplorer#18]
I have been trying to use the graph explorer, following the instructions in the QuickStart page of CosmosDB. I let the wizard create the DB. It create a GraphDB (Gremlin API). But the GraphExplorer application needs to connect to a DocumentDB. So the sample doesn't work, the loader cannot connect to the GraphDB. Am I doing/understanding something wrong

In addition, I am actually looking for a Graph Visualizer to visualize a GraphDB, using the `Gremlin.Net.Driver` API, **NOT** a DocumentDB using the `Microsoft.Azure.Graphs`. Does it exist ?

Thanks in advance.

**Comment by alexdrenea** [comment]
your question has 2 parts.
I will try and answer them separately:
1. The QuickStart does create a graph database which is what Graph Explorer needs to connect to. Can you provide more details about your connection string (endpoint) that you are using when setting up your graphexplroer instance?

2. On the `Gremlin.Net.Driver` vs `Microsoft.Azure.Graphs` i would recommend opening a separate ticket for that.

**Comment by philemon33** [comment]
Thanks Alex, I think I was making a huge confusion between DBs and APIs. After more reading, I was able to get the graph explorer connected to my DB. I also now grasp the difference between the two libraries.
