### ISSUE TITLE
Not able to build the project : Errors

### ISSUE THREAD

**Issue by SamirFarhat** [Azure-Samples/azure-cosmos-db-dotnet-graphexplorer#29]
Hi,
I'm using VS 2017 to build the project, but i continually get these errors during the build:
![image](https://user-images.githubusercontent.com/14938496/46144030-221e7000-c25c-11e8-8522-cb3b0b27b582.png)

**Comment by snerting** [comment]
Then we are two :-(

**Comment by igalshapira** [comment]
> update package.json (azure-cosmos-db-dotnet-graphexplorer\Web\GraphExplorer\package.json) webpack to: "webpack": "4.20.2",

This solved the issue for me

**Comment by Q4living** [comment]
This works, and you should update the package.json and push

**Comment by efficienthacks** [comment]
After changing the webpack version, you also have to do a "rebuild all"

**Comment by LuisBosquez** [comment]
Thanks for bringing this up. I just updated the dependencies.
