### ISSUE TITLE
Unable to build the project.Issue with Webpack

### ISSUE THREAD

**Issue by preshi** [Azure-Samples/azure-cosmos-db-dotnet-graphexplorer#35]
I am trying to build the project and observe the project is failing in build step when running the below step:

node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js

The error I observe is as below
<img width="731" alt="BuildError" src="https://user-images.githubusercontent.com/22865516/55239454-bb0a6400-525c-11e9-968c-ea2174e419ba.PNG">

**Comment by luddskunk** [comment]
I experience the same issue. I tried updating packages but I never to manage it. Even though the project is outdated and not ported to Gremlin.NET, I reckon I should still be able to run it.

Really looking forward to trying this!

 @LuisBosquez can you shed some light here?

**Comment by maxnorth** [comment]
For me downgrading the webpack version fixed it. Looks to me like they introduced [this change](https://github.com/Azure-Samples/azure-cosmos-db-dotnet-graphexplorer/commit/d393aebaa68b618e1678033c4eda920fa4301bc0) without re-testing the build and broke it. Reverting the package.json back to [this file](https://github.com/Azure-Samples/azure-cosmos-db-dotnet-graphexplorer/blob/e9203c32bad69d52bee931abfac9bb0cf392efa4/Web.NetCore/GraphExplorer/package.json) and re-running `npm install` before using webpack to rebuild it worked for me.

**Comment by preshi** [comment]
@maxnorth : Thanks for resolution. This is now making the Build Successful. But i am still not able to load the page. I observe that some of the required files in folder wwroot are missing. PFA for reference.Could you please confirm if you have observed similar issue.
<img width="853" alt="wwrootfilesmissing" src="https://user-images.githubusercontent.com/22865516/55573816-8ac53880-5728-11e9-8315-ee86a862f83b.PNG">

**Comment by maxnorth** [comment]
@preshi That's surprising, I haven't had any issues running it. I'm using [this package.json file](https://gist.github.com/maxnorth/a826856b86d0fcd5bc4ceb5d6706ee79) which has my own changes to decrease the webpack version, bump the typescript version (which resolved some other errors I was getting in the build output), and add build tasks. After the `npm install` I'm able to just use `npm run build` and `npm run build-vendor`, which drops the files you indicated are missing into the `wwwroot/dist` folder.

**Comment by preshi** [comment]
@maxnorth : Thank you. Your resolution solved the issue.Marking the issue as closed.
