### ISSUE TITLE
An Issue About Node in BuildTime

### ISSUE THREAD

**Issue by dimoibiehg** [Azure-Samples/azure-cosmos-db-dotnet-graphexplorer#5]
When I build the project, I have gotten the following errors:

1. Cannot find type definition file for 'node'
2. The command "node node_modules/webpack/bin/webpack.js" exited with code 2.

![image](https://user-images.githubusercontent.com/22638310/27987410-86161502-6422-11e7-888f-16c477aaa1ca.png)

I should have mentioned that run this command before: `npm install @types/node --save-dev`. My visual studio version is 2017 and node version is 6.11.

**Comment by dimoibiehg** [comment]
@mosesyap any comment?

**Comment by sbania** [comment]
@dimoibiehg , I have the same issue, tried to manually install the dependencies on the package.json but no luck.

**Comment by sstchur** [comment]
Sorry for the delay guys.  I'd like to help.  Can you tell me if you still see this error if in the Error List window in Visual Studio, you chance the drop that says "Build + Intellisense" to "Build Only"?

**Comment by sstchur** [comment]
Ok, after cloning the repo, I was able to repro the issue.  But commenting out this line in the tsconfig.json allowed me to build successfully. 

    //"types": [ "node" ]

Be sure to remove the trailing comma from the line above this one as well.  Then try rebuilding.  It worked for me.

**Comment by sbania** [comment]
thanks @sstchur , that did the trick

**Comment by xperiandri** [comment]
Why is it present at all if we comment it?

**Comment by sstchur** [comment]
It probably shouldn't be.  I need to change it and submit a PR.  Or someone else can and I will approve it.  Just been busy and haven't had a chance to create the PR.
