### ISSUE TITLE
Build Error - Cannot find type definition file for 'node'

### ISSUE THREAD

**Issue by cardiactwinky** [Azure-Samples/azure-cosmos-db-dotnet-graphexplorer#9]
I installed Node.js using the link in the readme, but I can't get past this error.  Any help would be appreciated. 

![image](https://user-images.githubusercontent.com/5509889/29230487-e4b7bdea-7ea8-11e7-9aef-b9d4359ed2fa.png)

**Comment by dimoibiehg** [comment]
Do you see [this issue](https://github.com/Azure-Samples/azure-cosmos-db-dotnet-graphexplorer/issues/5)?

**Comment by sstchur** [comment]
@cardiactwinky , if you are referring to the same issue @dimoibiehg linked to, I think this should be resolved (if you have latest from master).  If you have latest from master and are still seeing this, let me know.

**Comment by cool9brain** [comment]
Massive thank you. It worked

**Comment by alexdrenea** [comment]
Closing issue as it seems to have been fixed in PR.
